
# compiles the project including the profiler
all:

# makes the project ready to be submitted
pack:

# removes all files that should not be submitted
clean:

# runs math library tests
test:

# generates documentation
doc:

# runs the program
run:

# compiles the profiler
profile:


